// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	releasev1alpha1 "github.com/openshift/release-controller/pkg/apis/release/v1alpha1"
	scheme "github.com/openshift/release-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ReleasePayloadsGetter has a method to return a ReleasePayloadInterface.
// A group's client should implement this interface.
type ReleasePayloadsGetter interface {
	ReleasePayloads(namespace string) ReleasePayloadInterface
}

// ReleasePayloadInterface has methods to work with ReleasePayload resources.
type ReleasePayloadInterface interface {
	Create(ctx context.Context, releasePayload *releasev1alpha1.ReleasePayload, opts v1.CreateOptions) (*releasev1alpha1.ReleasePayload, error)
	Update(ctx context.Context, releasePayload *releasev1alpha1.ReleasePayload, opts v1.UpdateOptions) (*releasev1alpha1.ReleasePayload, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, releasePayload *releasev1alpha1.ReleasePayload, opts v1.UpdateOptions) (*releasev1alpha1.ReleasePayload, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*releasev1alpha1.ReleasePayload, error)
	List(ctx context.Context, opts v1.ListOptions) (*releasev1alpha1.ReleasePayloadList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *releasev1alpha1.ReleasePayload, err error)
	ReleasePayloadExpansion
}

// releasePayloads implements ReleasePayloadInterface
type releasePayloads struct {
	*gentype.ClientWithList[*releasev1alpha1.ReleasePayload, *releasev1alpha1.ReleasePayloadList]
}

// newReleasePayloads returns a ReleasePayloads
func newReleasePayloads(c *ReleaseV1alpha1Client, namespace string) *releasePayloads {
	return &releasePayloads{
		gentype.NewClientWithList[*releasev1alpha1.ReleasePayload, *releasev1alpha1.ReleasePayloadList](
			"releasepayloads",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *releasev1alpha1.ReleasePayload { return &releasev1alpha1.ReleasePayload{} },
			func() *releasev1alpha1.ReleasePayloadList { return &releasev1alpha1.ReleasePayloadList{} },
		),
	}
}
