// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/openshift/release-controller/pkg/apis/release/v1alpha1"
	scheme "github.com/openshift/release-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ReleasePayloadsGetter has a method to return a ReleasePayloadInterface.
// A group's client should implement this interface.
type ReleasePayloadsGetter interface {
	ReleasePayloads(namespace string) ReleasePayloadInterface
}

// ReleasePayloadInterface has methods to work with ReleasePayload resources.
type ReleasePayloadInterface interface {
	Create(ctx context.Context, releasePayload *v1alpha1.ReleasePayload, opts v1.CreateOptions) (*v1alpha1.ReleasePayload, error)
	Update(ctx context.Context, releasePayload *v1alpha1.ReleasePayload, opts v1.UpdateOptions) (*v1alpha1.ReleasePayload, error)
	UpdateStatus(ctx context.Context, releasePayload *v1alpha1.ReleasePayload, opts v1.UpdateOptions) (*v1alpha1.ReleasePayload, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ReleasePayload, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ReleasePayloadList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ReleasePayload, err error)
	ReleasePayloadExpansion
}

// releasePayloads implements ReleasePayloadInterface
type releasePayloads struct {
	client rest.Interface
	ns     string
}

// newReleasePayloads returns a ReleasePayloads
func newReleasePayloads(c *ReleaseV1alpha1Client, namespace string) *releasePayloads {
	return &releasePayloads{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the releasePayload, and returns the corresponding releasePayload object, and an error if there is any.
func (c *releasePayloads) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ReleasePayload, err error) {
	result = &v1alpha1.ReleasePayload{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("releasepayloads").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ReleasePayloads that match those selectors.
func (c *releasePayloads) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ReleasePayloadList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ReleasePayloadList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("releasepayloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested releasePayloads.
func (c *releasePayloads) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("releasepayloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a releasePayload and creates it.  Returns the server's representation of the releasePayload, and an error, if there is any.
func (c *releasePayloads) Create(ctx context.Context, releasePayload *v1alpha1.ReleasePayload, opts v1.CreateOptions) (result *v1alpha1.ReleasePayload, err error) {
	result = &v1alpha1.ReleasePayload{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("releasepayloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(releasePayload).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a releasePayload and updates it. Returns the server's representation of the releasePayload, and an error, if there is any.
func (c *releasePayloads) Update(ctx context.Context, releasePayload *v1alpha1.ReleasePayload, opts v1.UpdateOptions) (result *v1alpha1.ReleasePayload, err error) {
	result = &v1alpha1.ReleasePayload{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("releasepayloads").
		Name(releasePayload.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(releasePayload).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *releasePayloads) UpdateStatus(ctx context.Context, releasePayload *v1alpha1.ReleasePayload, opts v1.UpdateOptions) (result *v1alpha1.ReleasePayload, err error) {
	result = &v1alpha1.ReleasePayload{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("releasepayloads").
		Name(releasePayload.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(releasePayload).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the releasePayload and deletes it. Returns an error if one occurs.
func (c *releasePayloads) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("releasepayloads").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *releasePayloads) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("releasepayloads").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched releasePayload.
func (c *releasePayloads) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ReleasePayload, err error) {
	result = &v1alpha1.ReleasePayload{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("releasepayloads").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
