//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package notifications

import (
	jira "github.com/openshift/release-controller/pkg/releasequalifiers/notifications/jira"
	slack "github.com/openshift/release-controller/pkg/releasequalifiers/notifications/slack"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Notifications) DeepCopyInto(out *Notifications) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(slack.Notification)
		(*in).DeepCopyInto(*out)
	}
	if in.Jira != nil {
		in, out := &in.Jira, &out.Jira
		*out = new(jira.Notification)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Notifications.
func (in *Notifications) DeepCopy() *Notifications {
	if in == nil {
		return nil
	}
	out := new(Notifications)
	in.DeepCopyInto(out)
	return out
}
