//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package releasequalifiers

import (
	notifications "github.com/openshift/release-controller/pkg/releasequalifiers/notifications"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseQualifier) DeepCopyInto(out *ReleaseQualifier) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Approval != nil {
		in, out := &in.Approval, &out.Approval
		*out = new(bool)
		**out = **in
	}
	if in.FailureLabels != nil {
		in, out := &in.FailureLabels, &out.FailureLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(notifications.Notifications)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseQualifier.
func (in *ReleaseQualifier) DeepCopy() *ReleaseQualifier {
	if in == nil {
		return nil
	}
	out := new(ReleaseQualifier)
	in.DeepCopyInto(out)
	return out
}
