// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/release-controller/pkg/apis/release/v1alpha1"
	releasev1alpha1 "github.com/openshift/release-controller/pkg/client/clientset/versioned/typed/release/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeReleasePayloads implements ReleasePayloadInterface
type fakeReleasePayloads struct {
	*gentype.FakeClientWithList[*v1alpha1.ReleasePayload, *v1alpha1.ReleasePayloadList]
	Fake *FakeReleaseV1alpha1
}

func newFakeReleasePayloads(fake *FakeReleaseV1alpha1, namespace string) releasev1alpha1.ReleasePayloadInterface {
	return &fakeReleasePayloads{
		gentype.NewFakeClientWithList[*v1alpha1.ReleasePayload, *v1alpha1.ReleasePayloadList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("releasepayloads"),
			v1alpha1.SchemeGroupVersion.WithKind("ReleasePayload"),
			func() *v1alpha1.ReleasePayload { return &v1alpha1.ReleasePayload{} },
			func() *v1alpha1.ReleasePayloadList { return &v1alpha1.ReleasePayloadList{} },
			func(dst, src *v1alpha1.ReleasePayloadList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ReleasePayloadList) []*v1alpha1.ReleasePayload {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ReleasePayloadList, items []*v1alpha1.ReleasePayload) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
