// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ReleasePayloadListerExpansion allows custom methods to be added to
// ReleasePayloadLister.
type ReleasePayloadListerExpansion interface{}

// ReleasePayloadNamespaceListerExpansion allows custom methods to be added to
// ReleasePayloadNamespaceLister.
type ReleasePayloadNamespaceListerExpansion interface{}
