// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	releasev1alpha1 "github.com/openshift/release-controller/pkg/apis/release/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ReleasePayloadLister helps list ReleasePayloads.
// All objects returned here must be treated as read-only.
type ReleasePayloadLister interface {
	// List lists all ReleasePayloads in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*releasev1alpha1.ReleasePayload, err error)
	// ReleasePayloads returns an object that can list and get ReleasePayloads.
	ReleasePayloads(namespace string) ReleasePayloadNamespaceLister
	ReleasePayloadListerExpansion
}

// releasePayloadLister implements the ReleasePayloadLister interface.
type releasePayloadLister struct {
	listers.ResourceIndexer[*releasev1alpha1.ReleasePayload]
}

// NewReleasePayloadLister returns a new ReleasePayloadLister.
func NewReleasePayloadLister(indexer cache.Indexer) ReleasePayloadLister {
	return &releasePayloadLister{listers.New[*releasev1alpha1.ReleasePayload](indexer, releasev1alpha1.Resource("releasepayload"))}
}

// ReleasePayloads returns an object that can list and get ReleasePayloads.
func (s *releasePayloadLister) ReleasePayloads(namespace string) ReleasePayloadNamespaceLister {
	return releasePayloadNamespaceLister{listers.NewNamespaced[*releasev1alpha1.ReleasePayload](s.ResourceIndexer, namespace)}
}

// ReleasePayloadNamespaceLister helps list and get ReleasePayloads.
// All objects returned here must be treated as read-only.
type ReleasePayloadNamespaceLister interface {
	// List lists all ReleasePayloads in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*releasev1alpha1.ReleasePayload, err error)
	// Get retrieves the ReleasePayload from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*releasev1alpha1.ReleasePayload, error)
	ReleasePayloadNamespaceListerExpansion
}

// releasePayloadNamespaceLister implements the ReleasePayloadNamespaceLister
// interface.
type releasePayloadNamespaceLister struct {
	listers.ResourceIndexer[*releasev1alpha1.ReleasePayload]
}
